[package]
name = "nrf52840-blink"
version = "0.1.0"
edition = "2021"

[features]
default = [
    "defmt-default"
]

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.1"
defmt = "0.3.2"
defmt-rtt = "0.3.2"
nrf52840-hal = "0.15.1"
